services:
  mongodb:
    image: mongo:latest
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
